services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.6-alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx-proxy-net

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: letsencrypt
    restart: always
    depends_on:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - ACME_CA_URI=https://acme-v02.api.letsencrypt.org/directory
    volumes:
      - ./nginx/certs:/etc/nginx/certs:rw
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - nginx-proxy-net

  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: always
    environment:
      - VIRTUAL_HOST=dns.thundermiracle.com
      - LETSENCRYPT_HOST=dns.thundermiracle.com
      - LETSENCRYPT_EMAIL=info@thundermiracle.com
    volumes:
      - ./adguard-home/work:/opt/adguardhome/work
      - ./adguard-home/conf:/opt/adguardhome/conf
      - ./nginx/certs:/opt/adguardhome/ssl:ro
    networks:
      - nginx-proxy-net
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "853:853/tcp"     # DNS-over-TLS
      - "784:784/udp"     # DNS-over-QUIC
      - "8853:8853/udp"   # DNS-over-HTTPS
    cap_add:
      - NET_ADMIN

networks:
  nginx-proxy-net:
    driver: bridge
